#!/usr/bin/env python3
"""Extract application, token and login-pipeline configuration from the synthetic CLI fixtures.

Writes dist/app-config.js for the Applications tab (token lifetime matrix and login journey)
and for remediation snippets. Only Auth0 and Okta have fixtures; preview providers have none.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[3]
out = root / 'outputs/identity-pulse-demo/dist/app-config.js'
fixtures = {
    'auth0': {'risk': 'risky-tenant', 'healthy': 'healthy-tenant', 'partial': 'partial-scope'},
    'okta': {'risk': 'risky-org', 'healthy': 'healthy-org', 'partial': 'partial-scope-org'},
}
# Sections the Applications tab and remediation snippets read. None means "not collected".
keep = {
    'auth0': ['tenant', 'clients', 'connections', 'resourceServers', 'clientGrants', 'actions', 'rules', 'hooks',
              'guardian', 'attackProtection', 'prompts', 'customDomains', 'logStreams'],
    'okta': ['org', 'apps', 'policies', 'authenticators', 'authorizationServers', 'authorizationServerPolicies',
             'idps', 'eventHooks', 'inlineHooks', 'logStreams', 'domains', 'trustedOrigins', 'networkZones'],
}
data = {}
for provider, variants in fixtures.items():
    data[provider] = {}
    for sample, name in variants.items():
        snapshot = json.loads((root / f'fixtures/{provider}/{name}.snapshot.json').read_text())
        data[provider][sample] = {'source': f'fixtures/{provider}/{name}.snapshot.json',
                                  **{key: snapshot.get(key) for key in keep[provider]}}
out.write_text('/* Generated by support/generate-apps.py from synthetic CLI fixtures. Do not edit. */\n'
               'window.PULSE_APPS = ' + json.dumps(data, indent=1) + ';\n')
print(f'Wrote {out.relative_to(root)}')
